# Generated by Django 4.2.5 on 2023-10-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCrackers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
