# Generated by Django 4.2.6 on 2023-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCrackers', '0004_alter_cryptocurrency_ath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='fully_diluted_valuation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='max_supply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='total_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
