# Generated by Django 4.2.6 on 2023-10-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CryptoCrackers", "0007_alter_cryptocurrency_current_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
