# Generated by Django 4.2.6 on 2023-11-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCrackers', '0008_alter_userdetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='current_price_cad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='current_price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
