# Generated by Django 4.2.5 on 2023-11-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCrackers', '0013_userdetails_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
