# Generated by Django 4.2.6 on 2023-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCrackers', '0016_remove_transaction_currency_remove_wallet_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cryptocurrencies',
            field=models.JSONField(default=dict),
        ),
    ]
